export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS"
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE"

export const FETCH_TOKEN_REQUEST = "FETCH_TOKEN_REQUEST"
export const FETCH_TOKEN_SUCCESS = "FETCH_TOKEN_SUCCESS"
export const FETCH_TOKEN_FAILURE = "FETCH_TOKEN_FAILURE"

export const FETCH_USER_BY_TOKEN_REQUEST = 'FETCH_USER_BY_TOKEN_REQUEST'
export const FETCH_USER_BY_TOKEN_SUCCESS = "FETCH_USER_BY_TOKEN_SUCCESS"
export const FETCH_USER_BY_TOKEN_FAILURE = "FETCH_USER_BY_TOKEN_FAILURE"

export const FETCH_BOARDS_REQUEST = "FETCH_BOARDS_REQUEST"
export const FETCH_BOARDS_SUCCESS = "FETCH_BOARDS_SUCCESS"
export const FETCH_BOARDS_FAILURE = "FETCH_BOARDS_FAILURE"

export const FETCH_LISTS_REQUEST = "FETCH_LISTS_REQUEST"
export const FETCH_LISTS_SUCCESS = "FETCH_LISTS_SUCCESS"
export const FETCH_LISTS_FAILURE = "FETCH_LISTS_FAILURE"

export const FETCH_CARDS_REQUEST = "FETCH_CARDS_REQUEST"
export const FETCH_CARDS_SUCCESS = "FETCH_CARDS_SUCCESS"
export const FETCH_CARDS_FAILURE = "FETCH_CARDS_FAILURE"

export const CREATE_BOARD_REQUEST = "CREATE_BOARD_REQUEST"
export const CREATE_BOARD_SUCCESS = "CREATE_BOARD_SUCCESS"
export const CREATE_BOARD_FAILURE = "CREATE_BOARD_FAILURE"

export const CREATE_LIST_REQUEST = "CREATE_LIST_REQUEST"
export const CREATE_LIST_SUCCESS = "CREATE_LIST_SUCCESS"
export const CREATE_LIST_FAILURE = "CREATE_LIST_FAILURE"

export const CREATE_CARD_REQUEST = "CREATE_CARD_REQUEST"
export const CREATE_CARD_SUCCESS = "CREATE_CARD_SUCCESS"
export const CREATE_CARD_FAILURE = "CREATE_CARD_FAILURE"

export const CREATE_HISTORY_REQUEST = "CREATE_HISTORY_REQUEST"
export const CREATE_HISTORY_SUCCESS = "CREATE_HISTORY_SUCCESS"
export const CREATE_HISTORY_FAILURE = "CREATE_HISTORY_FAILURE"

export const SWITCH_BOARD = "SWITCH_BOARD"

export const EDIT_BOARD_REQUEST = "EDIT_BOARD_REQUEST"
export const EDIT_BOARD_SUCCESS = "EDIT_BOARD_SUCCESS"
export const EDIT_BOARD_FAILURE = "EDIT_BOARD_FAILURE"

export const EDIT_LIST_REQUEST = "EDIT_LIST_REQUEST"
export const EDIT_LIST_SUCCESS = "EDIT_LIST_SUCCESS"
export const EDIT_LIST_FAILURE = "EDIT_LIST_FAILURE"

export const EDIT_CARD_REQUEST = "EDIT_CARD_REQUEST"
export const EDIT_CARD_SUCCESS = "EDIT_CARD_SUCCESS"
export const EDIT_CARD_FAILURE = "EDIT_CARD_FAILURE"

export const DELETE_BOARD_REQUEST = "DELETE_BOARD_REQUEST"
export const DELETE_BOARD_SUCCESS = "DELETE_BOARD_SUCCESS"
export const DELETE_BOARD_FAILURE = "DELETE_BOARD_FAILURE"

export const DELETE_LIST_REQUEST = "DELETE_LIST_REQUEST"
export const DELETE_LIST_SUCCESS = "DELETE_LIST_SUCCESS"
export const DELETE_LIST_FAILURE = "DELETE_LIST_FAILURE"

export const DELETE_CARD_REQUEST = "DELETE_CARD_REQUEST"
export const DELETE_CARD_SUCCESS = "DELETE_CARD_SUCCESS"
export const DELETE_CARD_FAILURE = "DELETE_CARD_FAILURE"