export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS"
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE"

export const FETCH_BOARDS_REQUEST = "FETCH_BOARDS_REQUEST"
export const FETCH_BOARDS_SUCCESS = "FETCH_BOARDS_SUCCESS"
export const FETCH_BOARDS_FAILURE = "FETCH_BOARDS_FAILURE"

export const FETCH_LISTS = "FETCH_LISTS"
export const FETCH_LISTS_SUCCESS = "FETCH_LISTS_SUCCESS"
export const FETCH_LISTS_FAILURE = "FETCH_LISTS_FAILURE"

export const FETCH_CARDS = "FETCH_CARDS"
export const FETCH_CARDS_SUCCESS = "FETCH_CARDS_SUCCESS"
export const FETCH_CARDS_FAILURE = "FETCH_CARDS_FAILURE"

export const CREATE_BOARD = "CREATE_BOARD"
export const CREATE_BOARD_SUCCESS = "CREATE_BOARD_SUCCESS"
export const CREATE_BOARD_FAILURE = "CREATE_BOARD_FAILURE"

export const CREATE_LIST = "CREATE_LIST"
export const CREATE_LIST_SUCCESS = "CREATE_LIST_SUCCESS"
export const CREATE_LIST_FAILURE = "CREATE_LIST_FAILURE"

export const CREATE_CARD = "CREATE_CARD"
export const CREATE_CARD_SUCCESS = "CREATE_CARD_SUCCESS"
export const CREATE_CARD_FAILURE = "CREATE_CARD_FAILURE"

export const CREATE_HISTORY = "CREATE_HISTORY"
export const CREATE_HISTORY_SUCCESS = "CREATE_HISTORY_SUCCESS"
export const CREATE_HISTORY_FAILURE = "CREATE_HISTORY_FAILURE"

export const SWITCH_BOARD = "SWITCH_BOARD"

export const EDIT_BOARD = "EDIT_BOARD"
export const EDIT_BOARD_SUCCESS = "EDIT_BOARD_SUCCESS"
export const EDIT_BOARD_FAILURE = "EDIT_BOARD_FAILURE"

export const EDIT_LIST = "EDIT_LIST"
export const EDIT_LIST_SUCCESS = "EDIT_LIST_SUCCESS"
export const EDIT_LIST_FAILURE = "EDIT_LIST_FAILURE"

export const EDIT_CARD = "EDIT_CARD"
export const EDIT_CARD_SUCCESS = "EDIT_CARD_SUCCESS"
export const EDIT_CARD_FAILURE = "EDIT_CARD_FAILURE"

export const DELETE_BOARD = "DELETE_BOARD"
export const DELETE_BOARD_SUCCESS = "DELETE_BOARD_SUCCESS"
export const DELETE_BOARD_FAILURE = "DELETE_BOARD_FAILURE"

export const DELETE_LIST = "DELETE_LIST"
export const DELETE_LIST_SUCCESS = "DELETE_LIST_SUCCESS"
export const DELETE_LIST_FAILURE = "DELETE_LIST_FAILURE"

export const DELETE_CARD = "DELETE_CARD"
export const DELETE_CARD_SUCCESS = "DELETE_CARD_SUCCESS"
export const DELETE_CARD_FAILURE = "DELETE_CARD_FAILURE"